### ISSUE TITLE
Fix backport of bitcoin-core/secp256k1#925 (drop 'include/' prefix from -I)

### ISSUE THREAD

**Issue by mattiaferrari02** [BlockstreamResearch/secp256k1-zkp#208]
I have a few questions about the compilation of the project...

After running autogen and configure with the custom flags, at that point is it possible to compile the project without using the newly generated makefile (aka use directly the `gcc` command) or something like that.

I'm trying also to compile the project from xcode because I have the need to use this code in a swift library... the main problems encountered with the compilation from xcode are wrong includes in the files. I'm not an expert on AutoMake, but from what I have understood, all the includes are managed by automake, is there a way to do it manually?

**Comment by delta1** [comment]
> I'm trying also to compile the project from xcode because I have the need to use this code in a swift library 

What about compiling it "normally" with automake, and then dynamically linking it in your xcode project?

**Comment by real-or-random** [comment]
> In particular I'm referring to 
https://github.com/ElementsProject/secp256k1-zkp/blob/d22774e248c703a191049b78f8d04f37d6fcfa05/src/secp256k1.c#L9
>
> why the include is defined this way in this line?, but then
https://github.com/ElementsProject/secp256k1-zkp/blob/d22774e248c703a191049b78f8d04f37d6fcfa05/src/secp256k1.c#L36
>
> why this line doesn't use the `../` (I need to use the module generator)

This is because there have been changes in the upstream version of this library that apparently haven't properly been implemented in the modules that this fork contains... https://github.com/bitcoin-core/secp256k1/pull/925, https://github.com/bitcoin-core/secp256k1/pull/1126



> And then calling
>`gcc -Iinclude secp256k1.o test.c`  

This should help you: https://github.com/bitcoin-core/secp256k1/issues/929#issuecomment-997815459

**Comment by csjones** [comment]
> I also tried shipping the automake inside a swift library / pod, but they don't support that type of build, xcode expects to call the `xcodebuild` command and from what I found that behaviour isn't customizable.

Hey @mattiaferrari02 have you looked at the existing swift packages that wrap this project into spm?

**Comment by apoelstra** [comment]
I would consider our incorrect backport of https://github.com/bitcoin-core/secp256k1/pull/925 to be a bug that we should fix -- that PR was specifically to make cases like this easier to handle.

**Comment by real-or-random** [comment]
> Do you know anything about this error `illegal argument: !secp256k1_fe_is_zero(&ge->x)` ?

This indicates that you're using some API function with an incorrect argument. Figure out which API function throws that error and then have a look at the docs of this function in the header file.

**Comment by real-or-random** [comment]
> I would consider our incorrect backport of [bitcoin-core/secp256k1#925](https://github.com/bitcoin-core/secp256k1/pull/925) to be a bug that we should fix -- that PR was specifically to make cases like this easier to handle.

Let me reopen and repurpose this issue to track that bug.
