### ISSUE TITLE
Rebase onto libsecp256k1 release

### ISSUE THREAD

**Issue by Sjors** [BlockstreamResearch/secp256k1-zkp#212]
Now that libsecp256k1 [has release tags](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-December/021271.html), it would be good to rebase on those.

**Comment by real-or-random** [comment]
We now resynced with master (#260), and I think this makes sense, as long as we don't have releases here. (Perhaps we should have releases, but that's a separate issue...)
