### ISSUE TITLE
Musig: different agg_pk when pubkey_ptr sequences and verify failed

### ISSUE THREAD

**Issue by VantIer** [BlockstreamResearch/secp256k1-zkp#233]
Hi Sir:
  I am interested in musig and learning the code. 
  But I found when creating agg_pk with secp256k1_musig_pubkey_agg, different pubkey_ptr sequences result in different agg_pk and cache being generated.  Theoretically, it should be sequence-independent. At the same time this will cause the verification to fail. Is this a problem?

The code is in the examples/musig.c

**Comment by VantIer** [comment]
for example: pk_ptr as a,b,c,d and it will agg to X. But when pk_ptr as d,c,b,a , it will agg to Y different from X

**Comment by real-or-random** [comment]
This is intentionally, see the docs https://github.com/BlockstreamResearch/secp256k1-zkp/blob/master/include/secp256k1_musig.h#L208-L210 and https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki#design .

**Comment by VantIer** [comment]
> This is intentionally, see the docs https://github.com/BlockstreamResearch/secp256k1-zkp/blob/master/include/secp256k1_musig.h#L208-L210 and https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki#design .

Thank you very much.  I will study it carefully.  Thank you again.
