### ISSUE TITLE
Is the Musig code compatible with BIP 327?

### ISSUE THREAD

**Issue by ysangkok** [BlockstreamResearch/secp256k1-zkp#280]
I see no mention of the versions of BIP 327, so I am unsure whether the code has been updated to reflect the latest version of BIP 327.

**Comment by real-or-random** [comment]
Yes, see
https://github.com/BlockstreamResearch/secp256k1-zkp/blob/eb4fb6db0582fa9bc91ebbfa6f0a0079ce0a48f0/include/secp256k1_musig.h#L12-L15

https://github.com/BlockstreamResearch/secp256k1-zkp/pull/223 implemented rc4, and [rc4 is the same as v1](https://github.com/bitcoin/bips/blob/master/bip-0327.mediawiki#change-log).

**Comment by ysangkok** [comment]
Great, thank you!
